- README.md
can not install App using command
> bench --site sitename.localhost install-app builder
instead use
> bench --site sitename.localhost install-app website_builder
fixes https://github.com/frappe/builder/issues/3
> chore: Fix installation step in README.md

- builder/builder/doctype/builder_page/builder_page.json
- builder/builder/doctype/builder_page/builder_page.py
- builder/templates/generators/webpage.html
- frontend/src/components/BlockLayers.vue
- frontend/src/components/CodeEditor.vue
- frontend/src/components/PageScript.vue
- frontend/src/data/webPage.ts
- frontend/src/pages/PageBuilder.vue
- frontend/src/types/Builder/BuilderPage.ts
to open and close JS script panel, use "ctrl + `" shortcut (only way as of now.)
> feat: Rudimentary support for JS to make page interactive

- frontend/package.json
- frontend/src/components/TextBlock.vue
- frontend/src/index.css
- frontend/src/utils/block.ts
- yarn.lock
https://github.com/frappe/builder/assets/13928957/f21b4187-4bd2-43d3-bd65-45d14b2e79a7
- Supports creation of link inside text block (and introduced few quick toggles like bold, italics & strikethrough)
- Also, fixes the issue on new-line not getting rendered in the preview.
> feat: Support link creation in TextBlock

- frontend/src/components/BlockContextMenu.vue
- frontend/src/components/BlockEditor.vue
- frontend/src/components/BuilderCanvas.vue
- frontend/src/pages/PageBuilder.vue
- Context menu option to delete a block
- Fixed initial positioning of block while dragging movable block
- Make svg moveable and editable
> feat: Context menu option to delete a block

- builder/builder/doctype/builder_page/builder_page.py
- builder/utils.py
Allow limited functions to users who have server scripts disabled
```
frappe.db.count
frappe.db.exists
frappe.db.get_all (alias of safe_get_all)
frappe.db.get_list (alias of safe_get_all)
frappe.make_get_request (alias of make_safe_get_request)
frappe.get_doc (alias of get_doc_as_dict)
frappe.get_cached_doc (alias of get_cached_doc_as_dict)
```
> feat: Allow limited functions to users who have server scripts disabled

- frontend/src/components/BlockContextMenu.vue
- frontend/src/components/BlockLayers.vue
- frontend/src/components/BuilderBlock.vue
- frontend/src/components/BuilderCanvas.vue
- frontend/src/components/BuilderLeftPanel.vue
- frontend/src/components/TextBlock.vue
- frontend/src/pages/PageBuilder.vue
- frontend/src/store.ts
- frontend/src/utils/block.ts
- frontend/src/utils/blockController.ts
- frontend/src/utils/useDraggableBlock.ts
Each "block select" was triggering re-renders in all blocks due to usage of computed value in one of the prop. This made selection noticeably slow in complex/big web pages.
It is instant now.
> perf: Avoid re-rendering everything on select

- frontend/src/components/BuilderCanvas.vue
- frontend/src/pages/PageBuilder.vue
I component editing mode, we'll now have a button to save the component and breadcrumb to go back to the page editor.
> feat: Show "Save Component" button while editing component

- frontend/src/components/BuilderCanvas.vue
Fit width on initial load instead of considering the height of the page which ultimately scales down the canvas a lot.
> fix: Fit width on initial load

- builder/templates/generators/webpage.html
Load `csrf_token` to the page regardless of view_tracking flag
> fix: Load csrf_token to the page regardless of view_tracking flag

- .gitignore
I used the gitignore file to infer the build artifacts.
But these entries looked like legacy and where not intelligible in the context of the published build pipeline.
> chore: cleanup gitignore

- .pre-commit-config.yaml
- frontend/package.json
- frontend/vite.config.js
- fix: update prettier
- fix: build issue in alternative build root
- fix: repo folder can be distinct from app name
fixes: https://github.com/frappe/builder/issues/117
This uses the same strategy as `frappe-ui`.
> fix: Update build root

- frontend/src/components/TextBlock.vue
Previously, we used to wrap content inside new heading tags and update innerHTML (using tiptap's utility function) instead of updating the main block's element. This fix will update the tag of the main text block.
**Before:** 
**After:**
**Note:** To use this fix, you'll have to recreate your heading block.
closes: https://github.com/frappe/builder/issues/96
> fix: Update tag on toggling heading

- builder/html_preview_image.py
- builder/install.py
- builder/templates/generators/webpage.html
- requirements.txt
- setup.py
- Many users are unable to set dependencies for playwright properly which is why they have no preview.
We are using "preview.frappe.cloud" which is a frappe site with [preview_generator](https://github.com/frappe/preview_generator) app.
> feat: Use centralised preview generator to generate preview

- builder/builder/doctype/builder_page/builder_page.py
- frontend/src/components/BlockContextMenu.vue
- frontend/src/pages/PageBuilder.vue
- frontend/src/store.ts
- Due to cache, unpublished pages were visible for some time
- Unrelated fix: Allow copying style across pages
> fix: Instantly unpublish page on unpublishing from builder

- frontend/src/store.ts
Fetch latest doc to get correct route URL before publishing
> fix: Open correct url on hitting publish

- builder/builder/doctype/builder_page/builder_page.py
- frontend/src/components/BuilderBlock.vue
- frontend/src/utils/block.ts
This feature allows us to fetch dynamic value for a CSS property
https://github.com/frappe/builder/assets/13928957/30c9f59c-2132-4457-b5b7-154e7c4e64cb
> fix: Allow dynamic styles using Data Key

- yarn.lock
Missing lock file breaks sandboxed (no network, deps need to be available as per lock spec) builds.
Please consider cutting a patch release.
> hotfix: for v1.10.0

- README.md
- docker/docker-compose.yml
- docker/init.sh
Basic docker compose. Same one as other new products. Need to look into shipping HTTPS with this. 
Steps:
https://docs.frappe.io/builder/setting-up
> build: initial docker compose

- builder/builder/doctype/builder_page/builder_page.py
Creating this PR to allow route auto-generation only if the route is not already set.
To maintain all the builder pages in the repository we used the `bench export-fixtures` option.
Upon using the `bench migrate` on production environment all the routes auto-generated. Routes from the fixtures are not picked up.
To resolve the issue added a check in the `before_insert` method of `builder_page.py`.
This is to ensure that the fixtures import doesn't mess up the routes.
> fix: generate the route value only if self.route is empty

- builder/builder/doctype/builder_page/builder_page.py
- builder/templates/generators/webpage.html
Removed frappe-builder from class names to save some KBs. It also makes the DOM look cleaner ✨
On bigger pages with 500+ element the difference is noticeable!
**Before:**
**After:** (**-15KB** almost a size of small library!)
> perf: Remove frappe-builder from class names to save some KBs

- frontend/src/components/BlockEditor.vue
- frontend/src/components/BuilderBlock.vue
- frontend/src/components/TextBlock.vue
- frontend/src/store.ts
> fix(UX): Avoid outside click while selecting text

- frontend/src/components/BlockLayers.vue
- frontend/src/components/BuilderCanvas.vue
- frontend/src/store.ts
- frontend/src/utils/block.ts
Make traversing more natural i.e., selection based on visual sequence instead of hierarchy.
https://github.com/user-attachments/assets/0d7d8fb4-b24e-4ea6-b547-75a712857608
> feat: Directly use arrow keys to navigate blocks

- frontend/src/components/BlockLayers.vue
- frontend/src/components/BoxResizer.vue
- frontend/src/components/BuilderCanvas.vue
- frontend/src/components/Controls/ColorPicker.vue
- frontend/src/components/TextBlock.vue
- frontend/src/pages/PageBuilder.vue
- frontend/src/store.ts
- frontend/src/utils/block.ts
- frontend/src/utils/helpers.ts
- frontend/src/utils/useCanvasHistory.ts
- frontend/src/utils/useDraggableBlock.ts
This was done mainly to maintain the selected block states with canvasBlock snapshot so that affected block gets highlighted during undo and redo
- Fixed a case where duplicate snapshots was getting created while creating a new block
- This should also minimize storage required to store history snapshot by eliminating unnecessary data
> feat: Add custom history manager for canvas for more control

- builder/builder/doctype/builder_page/builder_page.py
To construct a UI like below
We often need to use `repeater` block, internally the repeater block define a key based on the blockKey, what create codes like
```jinja
{%- if not key_u7ps3awh6.price.unitary -%}
{%- if key_u7ps3awh6.price.monthly -%}
<h4>R$ {{ key_u7ps3awh6.price.monthly.real }}<sup style="font-weight: 200;">{{ key_u7ps3awh6.price.monthly.dec }}</sup>/<sub style="font-weight: 200;">mês</sub></h4>
{%- endif -%}
{%- if key_u7ps3awh6.price.yearly -%}
<h4>{%- if key_u7ps3awh6.price.monthly %} - {%- endif -%}R$ {{ key_u7ps3awh6.price.yearly.real }}<sup style="font-weight: 200;">{{ key_u7ps3awh6.price.yearly.dec }}</sup>/<sub style="font-weight: 200;">ano</sub></h4>
{%- endif -%}
{%- else -%}
<h4>R$ {{ key_u7ps3awh6.price.unitary.real }}<sup style="font-weight: 200;">{{ …
```
> Use block dataKey instead of block key for define for variable name

- frontend/src/components/BlockEditor.vue
- frontend/src/components/BorderRadiusHandler.vue
- frontend/src/components/BoxResizer.vue
- frontend/src/components/BuilderAssets.vue
- frontend/src/components/Modals/NewComponent.vue
- frontend/src/utils/block.ts
- frontend/src/utils/helpers.ts
- frontend/src/utils/useComponentStore.ts
- Fixed a case where overrides in nested component were not getting reflected during the usage
- Detach component option will only detach parent component instead of detaching all the nested component.
- Fixed a case where after creating a component and using it, changes to the component were not getting synced to the instance of the component.
- https://github.com/frappe/builder/pull/300/files#diff-e054a38b9c2a84b68fa62328ad66517a2cb01ff6054912208f3019dde5fbaabeR68 this change also improved the performance of the block loading since it is skips the reactive conversion overhead for referenceComponent for each block.
> fix: Component System

- frontend/src/components/BuilderBlockTemplates.vue
- frontend/src/components/BuilderToolbar.vue
- frontend/src/components/PublishButton.vue
- frontend/src/pages/PagePreview.vue
- frontend/src/store.ts
- If a page is not published
- If a page is published
- If a page is published and has some unpublished changes
**Note:** "Revert Changes" will discard all the changes done over the last published page and will give a warning before doing that.
> feat: Show revert change and unpublish button

- builder/templates/generators/webpage_scripts.html
This PR fixes an issue where the Builder edit icon was visible to users who don't have sufficient permissions to edit pages, such as Website Users. 
- Added an additional check in the editor icon condition to hide it for Website Users
- The icon will now only be displayed for System Users who have the necessary privileges
Previously, the edit icon was being displayed for all logged-in users, including Website Users who don't have permission to use Builder. This was confusing as clicking the icon would lead them to an access denied page.
- Login as a Website User and verify that the edit icon doesn't appear
- Login as a System User and verify that the edit icon still appears properly
> fix: Hide edit icon for Website Users

- frontend/src/components/BlockLayers.vue
- frontend/src/components/BuilderLeftPanel.vue
- frontend/src/components/Controls/CodeEditor.vue
**Before**
https://github.com/user-attachments/assets/f2916f07-758b-4345-b43a-fb2acdb1eca3
**After:**
https://github.com/user-attachments/assets/18939189-9eac-47c1-8b92-44e43a10dec1
> unrelated: Panel resize handle cursor does not show up for some reason while screen recording :/
> fix: Layer panel visibility for deeply nested layers

- frontend/src/components/BuilderCanvas.vue
- frontend/src/utils/useBlockEventHandlers.ts
- frontend/src/utils/useCanvasEvents.ts
- frontend/src/utils/useCanvasUtils.ts
The event listeners for the page canvas and the component editor canvas were both attached to the document, which caused unintended behavior. Even when the page canvas was hidden, its event listeners were still active and responding to events. As a result, interactions intended only for the active component editor canvas were also triggering the page canvas listeners. This led to issues like the `selectedBlockIds` list in the component editor canvas being incorrectly updated with block IDs from the page canvas 🤦‍♂️
> fix: Arrow navigation in component editor view

- frontend/src/App.vue
- frontend/src/components/BlockContextMenu.vue
- frontend/src/components/MainMenu.vue
- frontend/src/components/PageClientScriptManager.vue
- frontend/src/stores/builderStore.ts
- frontend/src/stores/canvasStore.ts
- frontend/src/stores/componentStore.ts
- frontend/src/stores/pageStore.ts
- frontend/src/utils/builderBlockCopyPaste.ts
- frontend/src/utils/helpers.ts
- frontend/src/utils/useBuilderEvents.ts
https://github.com/user-attachments/assets/3faded42-fe5b-4a5e-8903-89b68d13aacd
- Handled cases where copying back-n-forth between sites used to override components
- While copying blocks cross-site, all image or video sources will be updated to absolute URL to avoid broken image or video
- Introduced `showDialog` function to conveniently trigger custom dialogs via script
Copy from site to site
- normal w/o component ✅
- with component ✅
- no need to update or create ✅
- body copy
- page copy ✅
- with scripts ✅
- just block ✅
Copy from site to other site
- normal w/o component ✅
- normal with images (update URL) ✅
- with component (with deterministic new IDs) ✅
- update if exists ✅
- with nested components ⚠️ [not implemented]
- body copy
- page copy 
- with existing scripts (update …
> feat: Option to copy entire page with configuration and scripts

- builder/api.py
- builder/builder_analytics.py
- builder/hooks.py
- builder/patches.txt
- pyproject.toml
**Process:**
- All the records gets ingested to duckDB on migration and every 10 mins new records gets ingested
- Query directly on duckDB to get that performance: https://duckdb.org/why_duckdb#fast
> perf: Use duckdb for faster analytics

- README.md
- builder/builder/doctype/builder_page/builder_page.json
- builder/builder/doctype/builder_page/builder_page.py
- builder/builder/doctype/builder_settings/builder_settings.json
- builder/templates/generators/webpage.html
- frontend/src/components/Settings/GlobalGeneral.vue
- frontend/src/components/Settings/PageMeta.vue
- frontend/src/types/Builder/BuilderPage.ts
- frontend/src/types/Builder/BuilderSettings.ts
This PR adds the ability to configure the HTML lang attribute both globally and on a per-page basis, addressing the need for better internationalization support in Frappe Builder.
> feat: Option to set lang attribute to the page

- builder/builder/doctype/builder_page/builder_page.py
- builder/builder/doctype/builder_variable/builder_variable.py
- builder/templates/generators/webpage.html
- builder/www/builder_assets/color_scheme_variables.css
- builder/www/builder_assets/color_scheme_variables.py
- builder/www/builder_assets/variables.css
- builder/www/builder_assets/variables.py
The CSS variable logic has been moved out of the Builder Page and placed into a dedicated templated page. This ensures the latest CSS variables are loaded even when the page is cached on the server side. Previously, each Builder Page request triggered a `get_all` call to get variable list. Now, all variable-related logic is decoupled and cached separately... this eliminates redundant requests on page load.
> perf: Implement CSS variable caching
