frappe/builder

frontend/src/components/BlockProperties.vue, frontend/src/components/BuilderCanvas.vue, website_builder/website_builder/doctype/builder_page/builder_page.py
Any block can now render dynamic data from page context
=> feat: Support dynamic data without repeater

frontend/src/components/BlockProperties.vue, frontend/src/components/BuilderComponents.vue, frontend/src/components/CodeEditor.vue, frontend/src/components/ColorInput.vue, frontend/src/components/ObjectEditor.vue, frontend/src/components/OptionToggle.vue, frontend/src/pages/PageBuilder.vue
https://github.com/frappe/builder/assets/13928957/fb14ed2f-c6c0-424c-a1ec-9e78efd81e1e
> Had to refactor properties panel to achieve this (but LOC increased 🗿)
=> feat: Make properties panel searchable

builder/builder/doctype/builder_page/builder_page.py
=> fix: Remove unused import

frontend/src/pages/PageBuilderLanding.vue, frontend/src/utils/fontManager.ts
=> chore: Minor release

frontend/src/components/BlockLayers.vue, frontend/src/components/BuilderCanvas.vue, frontend/src/components/ObjectEditor.vue, frontend/src/components/TextBlock.vue, frontend/src/pages/PageBuilder.vue
[feat: Allow pasting key value pairs or object in ObjectEditor](https://github.com/frappe/builder/commit/d03546caa4925d24c03e695df41817fa91a2ad2e)
[fix: Set proper link on click check button](https://github.com/frappe/builder/commit/e81892e10210ac4b307b0802d64dbf6573caa823)
[fix: Show children if exists and do not let adding child to text, image and svg block](https://github.com/frappe/builder/pull/56/commits/68287738901d0e965f7d41e8ef220df9b28b6da4)
=> chore: Patch release

frontend/src/components/BlockEditor.vue, frontend/src/components/BuilderBlock.vue, frontend/src/components/CodeEditor.vue
Open code editor on double clicking HTML block
=> fix: Open code editor on double clicking HTML block

frontend/src/pages/PageBuilder.vue, frontend/src/utils/block.ts, frontend/src/utils/helpers.ts
- fixes: https://github.com/frappe/builder/issues/74
https://github.com/frappe/builder/assets/13928957/5f1fecda-9ef0-4050-a23f-32a867ce096a
- Option to detach component
https://github.com/frappe/builder/assets/13928957/45fb7488-807a-46ff-b672-8a9e60bf011c
=> fix: Detach component while copying child element

frontend/src/components/BlockContextMenu.vue, frontend/src/utils/block.ts
continuation of: https://github.com/frappe/builder/pull/77
=> feat: Option to detach component

.github/workflows/ci.yml, frontend/package.json, yarn.lock
CI should run in production mode
=> ci: Setup requirements in production mode

builder/builder/doctype/builder_page/builder_page.py
- This allows us to create a report based on specific event and properties adds option to add additional filter
=> fix: Set static event name and pass property

frontend/src/components/BlockProperties.vue, frontend/src/components/BuilderCanvas.vue, frontend/src/store.ts, frontend/src/utils/block.ts, frontend/src/utils/blockController.ts, frontend/src/utils/blockTemplate.ts
https://github.com/frappe/builder/assets/13928957/d910d4fa-1e5f-4782-bbcb-684626fb13d4
=> feat: Drop on canvas to upload a video

builder/builder/doctype/builder_page/builder_page.json, builder/builder/doctype/builder_page/builder_page.py, frontend/src/builder.d.ts, frontend/src/components/BuilderRightPanel.vue, frontend/src/components/OptionToggle.vue, frontend/src/components/PageOptions.vue, frontend/src/store.ts, frontend/src/types/Builder/BuilderPage.ts
https://github.com/frappe/builder/assets/13928957/b3e0a35d-fd4a-4621-9332-90065d9a2488
=> feat: Add option to set favicon per page

builder/builder/doctype/builder_page/builder_page.py, frontend/src/components/BuilderToolbar.vue, frontend/src/components/PageOptions.vue, frontend/src/store.ts
- Show option to unset home page
- Show "Homepage" badge if homepage is set
=> fix: Show option to unset home page

builder/builder/doctype/builder_page/builder_page.py, builder/builder/doctype/builder_settings/builder_settings.json, frontend/src/components/BlockProperties.vue, frontend/src/store.ts, frontend/src/types/Builder/BuilderSettings.ts
[BETA]
WebP images have relatively smaller size which improves the page load performance.
- Option to auto convert image to WebP
https://github.com/frappe/builder/assets/13928957/d8ccc6e5-6aa7-4b62-bdcc-068360b830c3
- Convert already uploaded image to WebP
https://github.com/frappe/builder/assets/13928957/b198edf4-ec1e-4263-8a52-599fb71b3898
=> feat: Option to auto convert images to WebP

frontend/src/App.vue, frontend/src/builder.d.ts, frontend/src/components/BlockEditor.vue, frontend/src/components/BuilderToolbar.vue, frontend/src/pages/PageBuilder.vue, frontend/src/router.ts, frontend/src/store.ts, frontend/src/usersInfo.ts, frontend/src/utils/realtimeHandler.ts
https://github.com/frappe/builder/assets/13928957/190dcdd1-0a9e-478e-932c-78832e3d3c18
This feature can be used as a precaution to prevent multiple people from editing and potentially overwriting each other's changes on the page until we have a better system to manage this scenario.
partially closes: https://github.com/frappe/builder/issues/160
=> feat: Show active users on editor

frontend/src/components/BlockLayers.vue, frontend/src/components/BuilderCanvas.vue, frontend/src/store.ts
https://github.com/frappe/builder/assets/13928957/17157905-078f-49f6-9bb6-ffb1013fee53
=> feat: Slide block into view on selection of block from layers panel

frontend/src/components/BlockContextMenu.vue, frontend/src/components/BlockLayers.vue, frontend/src/components/BuilderAssets.vue, frontend/src/components/BuilderCanvas.vue, frontend/src/data/webComponent.ts, frontend/src/pages/PageBuilder.vue, frontend/src/store.ts, frontend/src/types/Builder/BuilderComponent.ts, frontend/src/utils/block.ts, frontend/src/utils/helpers.ts
- Set parent in block to avoid lookup cost
- Refactor component management logic
=> perf: Set parent in block to avoid lookup cost

builder/api.py, builder/builder/doctype/builder_page/builder_page.py, frontend/package.json, frontend/src/components/BlockContextMenu.vue, frontend/src/components/BuilderCanvas.vue, frontend/src/components/BuilderToolbar.vue, frontend/src/components/ContextMenu.vue, frontend/src/components/PageClientScriptManager.vue, frontend/src/components/PageScript.vue, frontend/src/main.ts, frontend/src/pages/PageBuilderLanding.vue, frontend/src/pages/PagePreview.vue, frontend/src/store.ts, yarn.lock
- Only enables telemetry if it is enable via framework
- Added few basic custom events for analysis of builder usage.
=> feat: Init posthog telemetry to analyse builder usage

frontend/src/components/CodeEditor.vue, frontend/src/components/PageClientScriptManager.vue, frontend/src/components/PageScript.vue, frontend/src/pages/PageBuilder.vue
- Give explicit save button (no more auto-save magic for code)
- Avoid undo that removes all the code from the editor
- Toast to show successful code save
- Descriptive error message to find out what went wrong
- Enable search in code editor
- Move description, label and save button inside code editor component
=> refactor(code-editor): UX enhancements

builder/builder/doctype/builder_page/builder_page.py
backport of https://github.com/frappe/builder/pull/203
=> fix: generate the route value only if self.route is empty

builder/api.py, builder/builder/doctype/builder_page/builder_page.py, builder/builder/test_utils.py, builder/utils.py, frontend/src/components/BlockProperties.vue, frontend/src/pages/PagePreview.vue, frontend/src/store.ts
- Utility methods to utils.py
- Methods accessible through via API to api.py
=> refactor: Move methods to appropriate files

builder/api.py, frontend/src/store.ts
To avoid accidental changes in the existing script. Since the users expect scripts to be duplicated as well.
- One problem with this is it'll create unnecessary duplicates
=> fix(UX): Duplicate scripts while duplicating a page

builder/api.py, frontend/src/App.vue, frontend/src/components/DashboardSidebar.vue, frontend/src/components/EditableSpan.vue, frontend/src/components/PageClientScriptManager.vue
- For folder
- For page scripts
=> fix: Add rename and delete options

builder/builder/doctype/builder_page/builder_page.json, builder/builder/doctype/builder_page/builder_page.py, builder/builder/doctype/builder_page_library/builder_page_library.json, builder/builder/doctype/builder_page_library/builder_page_library.py, builder/builder/doctype/builder_settings/builder_settings.json, builder/templates/generators/webpage.html, builder/templates/generators/webpage_scripts.html, frontend/src/components/Controls/CodeEditor.vue, frontend/src/components/PageScript.vue, frontend/src/components/Settings.vue, frontend/src/components/Settings/GlobalCode.vue, frontend/src/components/Settings/PageCode.vue, frontend/src/data/builderPageLibrary.ts, frontend/src/types/Builder/BuilderPage.ts, frontend/src/types/Builder/BuilderPageLibrary.ts, frontend/src/types/Builder/BuilderSettings.ts
https://github.com/user-attachments/assets/1f5a365c-6372-4b21-be89-c386e43b8e62
=> feat: Option append HTML directly to the head and body

frontend/src/components/BlockPropertySections/OptionsSection.ts
add a `canvas` option to list of html tags
closes #318
=> feat: add `canvas` option to list of html tags

frontend/src/components/BuilderCanvas.vue, frontend/src/components/Controls/DraggablePopup.vue, frontend/src/components/Controls/SearchBlock.vue, frontend/src/pages/PageBuilder.vue, frontend/src/stores/builderStore.ts, frontend/src/utils/useBuilderEvents.ts
Very basic implementation to search a block in canvas. 
https://github.com/user-attachments/assets/91890675-902d-40ab-90b4-b64e603460da
- Also, introduced Draggable Popup 
Note: 
- Search popup gets triggered with `cmd/ctrl+shift+f`
- Need to add more granularity. Can be another PR
=> feat: Option to search a block in canvas

builder/api.py, frontend/src/components/BuilderSettings.vue, frontend/src/components/Settings/PageAnalytics.vue
- Show total views and unique views for a specified intervals
=> feat: Init basic analytics

builder/builder/doctype/builder_page/test_builder_page.py
Test cases to test 
- Dynamic value mapping
- Data repeater
=> test: Add test cases to test dynamic values

frontend/src/components/Settings/AnalyticsFilters.vue, frontend/src/components/Settings/AnalyticsOverview.vue, frontend/src/components/Settings/GlobalAnalytics.vue, frontend/src/components/Settings/PageAnalytics.vue, frontend/src/composables/useAnalytics.ts
https://github.com/user-attachments/assets/ff6ff8d1-8130-4097-b24a-d4b333f90338
- Drill-down to get data for specific date range
- Removed unnecessary interval filter. It gets auto selected based on date range
=> feat(Analytics): Drill-down to get data for specific date range

frontend/package.json, frontend/src/utils/createCodeMirrorState.ts, yarn.lock
Overview:
- fix cut behaviour
- add conditional line-wrapping
- fix "tab" keypress behaviour
- add indentation markers
Description:
This PR fixes the unexpected cut behaviour which propagated from the editor to the document and triggered block-level cut:
Before (cutting without selection propagates and cuts the selected block):
https://github.com/user-attachments/assets/29a5bdd6-894c-4d03-bba6-8909ff4fb120
After:
https://github.com/user-attachments/assets/b3ec4c9b-4540-4485-b801-cc8eac8d476c
This PR also introduces conditional line-wrapping (enabled if line numbers are also shown):
Before:
https://github.com/user-attachments/assets/2717625c-3f64-44a6-84c5-69c1475074a5
After:
Also fixes "tab" keypress behaviour:
Before:
https://github.com/user-attachments/assets/0d1ef637-27f1-4ddc-b0dc-6b6c …
=> fix(code-editor): Misc
